spring:
  flyway:
    clean-disabled: true

  jpa:
    show-sql: false

  datasource:
    url: ${SPRING_DATABASE_URL}
    username: ${SPRING_DATABASE_USERNAME}
    password: ${SPRING_DATABASE_PASSWORD}
  mail:
    host: ${SMTP_HOST}
    port: ${SMTP_PORT}
    username: ${SMTP_USER}
    password: ${SMTP_PASSWORD}
    properties:
      mail:
        debug: false

wutsi:
  client-id: wutsi-chat
  platform:
    security:
      type: jwt
      api-key: ${API_KEY}
    messaging:
      sms:
        type: aws
        aws:
          region: us-east-1
      push:
        type: firebase
        firebase:
          credentials: ${FIREBASE_CREDENTIALS}
      url-shortener:
        type: bitly
        bitly:
          access-token: ${BITLY_ACCESS_TOKEN}
      whatsapp:
        type: cloud
          cloud:
            access-token: ${WHATSAPP_ACCESS_TOKEN}
            phone-id: ${WHATSAPP_PHONE_ID}
    stream:
      type: rabbitmq
      rabbitmq:
        url: ${CLOUDAMQP_URL}

